delete_list = ['Defi', "Heaven", "Etherium", "The Metaverse Store", "Black Hole", 'Gass',
               'Singapore(S/D)(way-3)', 'Pets from all over the world',
               'Polygyros', 'Everywhere', 'Indonesian', 'WEB3', 'Hotel International',
               'Embassy of Ukraine', 'Computer', 'Milky Way Galaxy Spot', 'I don’t know',
               'Galaxy Space', 'Find me', 'Switch Yard', 'Satoshi Nakamoto',
               'XD', 'The World', 'In Space', "DMCC", 'God', 'Nyan', 'Métamé', 'Dogé دوقي',
               'My Sweet Home', 'Sumber', 'Sky', "I'll be the wings that keep your heart in the clouds",
               'Digital Arts and Humanities Active Learning Space', 'Cork', 'Online Services', 'Irish World Academy of Music and Dance',
               'Ard', 'Inevitable', 'Man of the world', 'Cosmos', 'Eu', 'New Planet', 'Wild Wild West', 'X',
               'Five', "Tron", 'Exchange', 'Border', 'Error', 'HELL TOUR', 'Here', 'IN', 'Hogwarts', 'LocalHost', 'Art World',
               'Warzone', 'On', 'Whale', 'Multiverse', 'Here', 'South', 'Northwest', 'Nfa', 'Meme',
               'Littoral', 'bitcoin', 'Bitcoin ATM', 'Slum', 'Root', 'Your House', 'Solo', 'Fantasy','Community (DK26)',
               'rubbish',  'Community (TK31)', 'Space Towers 1', 'Space Towers 2', 'Space Towers 3',
               'Lottery', 'Go Anywhere Slab',  'Wow','nonce', 'Other World',  'In front of you there is...',
               'ZZ', 'Saturnus', 'D', 'If', 'Web', 'On the way', 'Where', 'Bull', 'Goe',
               'No. Zero - Knowledge Centre', 'North', 'East', 'Universe', 'PHO HA NOI', 'Balagan',
               'Building', 'The Boredroom', 'Ask me:)', 'CHN', 'Cyber World', 'Ministry of Decentralization and Territorial Administration',
               'Cyber', 'XYZ', 'Checkmate', 'Bar', 'NewYork', 'Node', 'Empty', 'Bananaville',
               'Not Worthy of a Name Lookout', 'Garage', 'Jungle', 'Kalifonia', 'COMING SOON', 'In Time',
               'Ibb Governorate', 'KFC', '9999', 'Sushi Goooo', 'West', 'Centre Department', 'Blue', 'Degens',
               'Only God', ]